var guests4 = ["Bisma", "Kinza", "Kainat"];
var notJoining2 = "Kainat";
var newGuest4 = "Zehra";
guests4[guests4.indexOf(notJoining2)] = newGuest4;
console.log("Welcome all! To informing that we found a bigger dinner table.");
guests4.unshift("Bushra");
var middleGuest1 = "Hoorain";
var middleindex1 = guests4.length / 2;
guests4.splice(middleindex1, 0, middleGuest1);
guests4.push("Ayat");
var invitationMessage = "You are invited at our home for dinner.";
guests4.map(function (item) { return console.log(item, "You are invited at our home for dinner."); });
